In [11]:
import numpy as np
from sklearn.svm import SVC

In [21]:
svm = SVC(gamma='auto', kernel='linear')
X = np.array([[0,0],[1,2],[-1,2]])
y = np.array([-1,1,1])

In [22]:
s = svm.fit(X,y)

In [25]:
s.coef_

array([[3.840000e-04, 1.000192e+00]])

In [26]:
s.intercept_

array([-1.000256])

In [24]:
s.dual_coef_

array([[-0.500096,  0.25024 ,  0.249856]])

For the dual coef. there is minus in front as they are multiplied with y. Other than that, values are almost the same up to numerical imprecisions (e.g. w_0 is 0 in analytical but 0.000384)